# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Julia Belyakova
tagline:          'Tagline'
description:      'Description'
url:              https://julbinb.github.io

author:
  name:           'Julia Belyakova'
  url:            https://twitter.com/julbinb

#paginate:         5
#paginate_path:    '/blog/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
#sidebar_blog_link:  '/blog'

github:
  account:          https://github.com/julbinb/
  repo:             https://github.com/julbinb/julbinb.github.io
